//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_City
    {
        public tbl_City()
        {
            this.tbl_PostedJobs = new HashSet<tbl_PostedJobs>();
            this.tbl_Candidate = new HashSet<tbl_Candidate>();
        }
    
        public long ID { get; set; }
        public string City { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
    
        public virtual ICollection<tbl_PostedJobs> tbl_PostedJobs { get; set; }
        public virtual ICollection<tbl_Candidate> tbl_Candidate { get; set; }
    }
}
